const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/skillBarter', { useNewUrlParser: true, useUnifiedTopology: true });

const Hobby = require('../back/models/user');

const hobbies = [
  {
    email: 'anna@gmail.com',
    login: 'annutka',
    password: '1',
    name: 'Анна',
    photo: null,
    hobby: 'готовить',
    wish: 'плавать',
    phone: '9261112233',
    sex: 'женский',
    city: 'Москва',
    age: '23',
  },
  {
    email: 'max@gmail.com',
    login: 'max',
    password: '2',
    name: 'Максим',
    photo: null,
    hobby: 'плавать',
    wish: 'готовить',
    phone: '9162233344',
    sex: 'мужской',
    city: 'Москва',
    age: '33',
  },
  {
    email: 'masha@gmail.com',
    login: 'mashutka',
    password: '3',
    name: 'Маша',
    photo: null,
    hobby: 'рисовать',
    wish: 'плавать',
    phone: '7158889965',
    sex: 'женский',
    city: 'Москва',
    age: '42',
  },
  {
    email: 'luda@gmail.com',
    login: 'ludka',
    password: '4',
    name: 'Люда',
    photo: null,
    hobby: 'рисовать',
    wish: 'танцевать',
    phone: '7158889943',
    sex: 'женский',
    city: 'Москва',
    age: '46',
  },
  {
    email: 'sasha@gmail.com',
    login: 'sashka',
    password: '5',
    name: 'Александра',
    photo: null,
    hobby: 'танцевать',
    wish: 'рисовать',
    phone: '6611111111',
    sex: 'женский',
    city: 'Москва',
    age: '18',
  },
  {
    email: 'oleg@gmail.com',
    login: 'olejka',
    password: '6',
    name: 'Олег',
    photo: null,
    hobby: 'готовить',
    wish: 'танцевать',
    phone: '6690901111111',
    sex: 'женский',
    city: 'Москва',
    age: '38',
  },
  {
    email: 'lexa@gmail.com',
    login: 'lexa',
    password: '7',
    name: 'Алексей',
    photo: null,
    hobby: 'петь',
    wish: 'плавать',
    phone: '6611111111',
    sex: 'женский',
    city: 'Москва',
    age: '51',
  },
  {
    email: 'lisha@gmail.com',
    login: 'lisha',
    password: '8',
    name: 'Алексей',
    photo: null,
    hobby: 'петь',
    wish: 'танцевать',
    phone: '660000001111',
    sex: 'мужской',
    city: 'Москва',
    age: '74',
  },
  {
    email: 'katya@gmail.com',
    login: 'Katya',
    password: '9',
    name: 'Екатерина',
    photo: null,
    hobby: 'танцевать',
    wish: 'петь',
    phone: '6600001111',
    sex: 'женский',
    city: 'Москва',
    age: '24',
  },
  {
    email: 'kotya@gmail.com',
    login: 'Kotya',
    password: '10',
    name: 'Екатерина',
    photo: null,
    hobby: 'рисование',
    wish: 'готовить',
    phone: '6111',
    sex: 'женский',
    city: 'Москва',
    age: '29',
  },

  {
    email: 'kostya@gmail.com',
    login: 'Kostya',
    password: '10',
    name: 'Константин',
    photo: null,
    hobby: 'петь',
    wish: 'танцевать',
    phone: '61111233321',
    sex: 'женский',
    city: 'Москва',
    age: '42',
  },
];

Hobby.insertMany(hobbies).then(() => {
  mongoose.connection.close();
});
