export const PROFILE_USER = 'PROFILE_USER';
export const FIND_TEACHERS = 'FIND_TEACHERS';
export const TEACHERS_FULLMATCH = 'TEACHERS_FULLMATCH';
export const TEACHERS_FROMSEARCH = 'TEACHERS_FROMSEARCH';
